replicaCount: 1

namespace: websvc-env

hosts:
  main_url: "1st.url"
  second_url: "2sd.url" 

image:
  repository: "metairie/websvc-env"
  pullPolicy: IfNotPresent
  tag: "0.0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
serviceAccount:
  create: false

services:
  type: NodePort
  svc:
    - name: websvc-env
      port: 8000
      targetport: 8000
      protocol: TCP
      nodeport: 32000

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}